### ISSUE TITLE
host collections not listed with want_hostcollections unless use_reports_api is included

### ISSUE THREAD

**Issue by taftsanders** [RedHatSatellite/satellite-ansible-collection#33]
##### SUMMARY
Maybe the expectation is wrong, but with the `want_hostcollections: true` option there are no host collection groups being created. Once the `use_reports_api: true` in addition to `want_hostcollections: true` option is added the host collection group is created. I wasn't able to find anything that mentioned this as a required option for want_hostcollections to work.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.9.22
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### COLLECTION VERSION

```
# ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')

```

##### KATELLO/FOREMAN VERSION

```
# rpm -q tfm-rubygem-katello foreman
tfm-rubygem-katello-3.18.1.32-1.el7sat.noarch
foreman-2.3.1.21-1.el7sat.noarch

```

##### STEPS TO REPRODUCE

1) Install the ansible collections RPM on Satellite:
# satellite-maintain packages install ansible-collection-redhat-satellite
*Note: this was also tested with version 2.1.2 from https://cloud.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/import-log

2) Create a foreman.yml file with the options I want:
# cat foreman.yml 
plugin: redhat.satellite.foreman
validate_certs: False
url: https://satellite.zircon.local
user: admin
password: redhat
cache: no
want_hostcollections: true
###use_reports_api: true

3) I can see host vm77.zircon.local is in the host collection test_host_collection_1 from the hammer output:
[root@satellite ansible]# hammer host info --id 7
Id:                       7
Name:                     vm77.zircon.local
Organization:             Default Organization
Location:                 Default Location
Puppet Environment:       production
Puppet CA Proxy:          satellite.zircon.local
Puppet Master Proxy:      satellite.zircon.local
Cert name:                vm77.zircon.local
Managed:                  yes
--snip--
Host Collections:         
 1) Id:   1
    Name: test_host_collection_1   <<<<<<<<HERE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4) Pull ansible inventory:
# ansible-inventory -i foreman.yml --list
--snip--
    }, 
    "all": {
        "children": [ 
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "capsule1.zircon.local", 
            "capsule2.zircon.local", 
            "capsulelb.zircon.local", 
            "dns.zircon.local", 
            "pulp.zircon.local", 
            "pulp3.zircon.local", 
            "satellite.zircon.local", 
            "virt-who-odin-1", 
            "virt-who-odin-1.zircon.local", 
            "virt-who-titan-1", 
            "virt-who-titan-3", 
            "virt-who-titan.cluster.local-1"
        ]
    }
}

Output with `use_reports_api: true`:
# ansible-inventory -i foreman.yml --list
--snip--
    }, 
    "all": {
        "children": [
            "foreman_hostcollection_test_host_collection_1", 
            "ungrouped"
        ]
    }, 
    "foreman_hostcollection_test_host_collection_1": {
        "hosts": [
            "vm511.zircon.local", 
            "vm610.zircon.local", 
            "vm77.zircon.local", 
            "vm83.zircon.local"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "capsule1.zircon.local", 
            "capsule2.zircon.local", 
            "capsulelb.zircon.local", 
            "dns.zircon.local", 
            "pulp.zircon.local", 
            "pulp3.zircon.local", 
            "satellite.zircon.local", 
            "virt-who-odin-1", 
            "virt-who-odin-1.zircon.local", 
            "virt-who-titan-1", 
            "virt-who-titan-3", 
            "virt-who-titan.cluster.local-1"
        ]
    }
}

```yaml

```

##### EXPECTED RESULTS

Looking to confirm is the use of `use_reports_api: true` is expected to be needed for `want_hostcollections` to work properly

##### ACTUAL RESULTS

```

```

**Comment by wbclark** [comment]
Hi @taftsanders ! Thanks for the issue report.

Looking in https://github.com/theforeman/foreman-ansible-modules/blob/develop/plugins/inventory/foreman.py I see that there is logic in both the `_populate_report_api` and `_populate_host_api` methods to build ansible groups from hostcollections (in each case, it's under `if self.get_option('want_hostcollections')`. So it's clear that this feature should work with either host or reports API, or was at least intended to at one point.

I see also that the minimum foreman version for the reports API is 1.24 so in your case with foreman 2.3, using the reports API should be a viable workaround. What I'm less sure about is whether there is any advantage to continue using the Hosts API with newer Foreman versions or if backwards compatibility is the only reason it is still present (this is my intuition, but I don't really know the history behind it).

Could you please file an issue at https://github.com/theforeman/foreman-ansible-modules/issues and close the issue here? NOTE: that one is the upstream repository for this collection where active development takes place. This repository here is basically used to streamline the process of re-branding and releasing the downstream version of the collection only, and it's unlikely that someone else would see this issue.

**Comment by taftsanders** [comment]
Hey @wbclark Will do thanks!
